name: flutter_appauth_example
description: Demonstrates how to use the flutter_appauth plugin.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.0
  flutter_appauth_platform_interface: ^6.0.0
  url_launcher: ^6.1.14
  openid_client: ^0.4.8
  get_it: ^7.6.4

  flutter:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bank_logos/
    - assets/favourite_logos/
